import { ServerPermissions } from "../types/permissions";

interface Role {
  name: string;
  permissions: ServerPermissions[];
}

export const roles: Record<string, Role> = {
  admin: {
    name: "admin",
    permissions: [
      "read:users",
      "write:users",
      "update:users",
      "read:posts",
      "write:posts",
      "update:posts",
      "delete:posts",
      "read:comments",
      "write:comments",
      "update:comments",
      "delete:comments",
      "read:likes",
      "write:likes",
      "update:likes",
      "delete:likes",
      "read:chats",
      "write:chats",
      "update:chats",
      "delete:chats",
      "read:products",
      "write:products",
      "update:products",
      "delete:products",
    ],
  },
  seller: {
    name: "seller",
    permissions: [
      "read:posts",
      "write:posts",
      "update:posts",
      "delete:posts",
      "read:comments",
      "write:comments",
      "update:comments",
      "delete:comments",
      "read:chats",
      "write:chats",
      "update:chats",
      "delete:chats",
      "read:likes",
      "write:likes",
      "update:likes",
      "delete:likes",
      "read:users",
      "read:products",
      "write:products",
      "update:products",
      "delete:products",
    ],
  },
  user: {
    name: "user",
    permissions: [
      "read:users",
      "read:posts",
      "write:posts",
      "update:posts",
      "delete:posts",
      "read:comments",
      "write:comments",
      "update:comments",
      "delete:comments",
      "read:likes",
      "write:likes",
      "update:likes",
      "delete:likes",
      "read:chats",
      "write:chats",
      "update:chats",
      "delete:chats",
      "read:products",
      "update:products",
    ],
  },
  guest: {
    name: "guest",
    permissions: ["read:posts", "read:comments", "read:likes", "read:products"],
  },
};
