export const FORUM_CATEGORIES = [
  { key: "pregnancy", value: "Pregnancy" },
  { key: "newborn_care", value: "Newborn Care" },
  { key: "breastfeeding", value: "Breastfeeding" },
  { key: "formula_feeding", value: "Formula Feeding" },
  { key: "sleep_tips", value: "Sleep Tips" },
  { key: "baby_health", value: "Baby Health" },
  { key: "toddler_development", value: "Toddler Development" },
  { key: "parenting_advice", value: "Parenting Advice" },
  { key: "nutrition_recipes", value: "Nutrition & Recipes" },
  { key: "postpartum_support", value: "Postpartum Support" },
  { key: "mental_health", value: "Mental Health" },
  { key: "work_life_balance", value: "Work-Life Balance" },
  { key: "baby_gear_products", value: "Baby Gear & Products" },
  { key: "milestones_growth", value: "Milestones & Growth" },
  { key: "child_safety", value: "Child Safety" },
  { key: "education_learning", value: "Education & Learning" },
  { key: "family_activities", value: "Family Activities" },
  { key: "single_parenting", value: "Single Parenting" },
  { key: "special_needs", value: "Special Needs" },
  { key: "multiples", value: "Multiples (Twins, Triplets, etc.)" },
  { key: "dads_partners", value: "Dads & Partners" },
  { key: "adoption_fostering", value: "Adoption & Fostering" },
  { key: "community_support", value: "Community Support" },
  { key: "local_resources", value: "Local Resources" },
  { key: "toys_play", value: "Toys and Play" }
];
